services:
  - type: web
    name: wedding-bot
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/wedding-bot-1.0.0.jar
    envVars:
      - key: JAVA_VERSION
        value: "15"