services:
  - type: web
    name: wedding-bot
    env: java        # Важно: окружение Java!
    plan: free
    buildCommand: ./mvnw clean install  # Используем Maven Wrapper
    startCommand: java -jar target/wedding-bot-1.0.0.jar  # Имя из pom.xml