services:
  - type: web
    name: wedding-bot
    env: java
    plan: free
    region: frankfurt  # Опционально: выберите ближайший регион
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/wedding-bot-1.0.0.jar
    envVars:
      - key: SERVER_PORT
        value: 8080